[package]
name = "vmu"
version = "0.1.0"
authors = ["maxpr"]
edition = "2018"

[dependencies]
serialport = "3.3.0"
winapi = { version = "0.3.7", features = ["winuser", "objbase", "mmdeviceapi", "endpointvolume"] }
